<center><u><H1>Singlar Value Decomposition</H1></u></center>

Singular value decomposition is a method of decomposing a matrix into three other matrices:<br><br>
<center><b><h1> A = U . S. V^T </h1></b> </center>
<br>
Where:<br>

A is an m × n matrix <br>
U is an m × m orthogonal matrix  (left singular vector)<br>
S is an m × n diagonal matrix with non-negative real numbers<br>
V is an n × n orthogonal matrix (right singular vector)<br><br>
The diagonal values of S are known as Singular values of A.

## Calculate Singular-Value Decomposition

In [6]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd

# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])

print("Original matrix: \n", A)

# SVD
U, s, VT = svd(A)

# Here s = The singular values, sorted in non-increasing order. Of shape (K,), with K = min(M, N).

print("Othogonal matrix: \n",U)
print("Diagonal matrix: \n",s)
print("Orthogonal matrix: \n",VT)

Original matrix: 
 [[1 2]
 [3 4]
 [5 6]]
Othogonal matrix: 
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Diagonal matrix: 
 [9.52551809 0.51430058]
Orthogonal matrix: 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


## Reconstruct original matrix from SVD

In [12]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd

# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])

print(A)

# Singular-value decomposition
U, s, VT = svd(A)

# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
print("Sigma: \n",Sigma)
print("Diagonal of s: \n",diag(s))

# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
print("Sigma: \n",Sigma)

# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print("Reconstructed Matrix: \n",B)

[[1 2]
 [3 4]
 [5 6]]
Sigma: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Diagonal of s: 
 [[9.52551809 0.        ]
 [0.         0.51430058]]
Sigma: 
 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]
Reconstructed Matrix: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


## Calculate Pseudo-inverse of a matrix

In [13]:
 from numpy import array
from numpy.linalg import pinv

# define matrix
A = array([
	[0.1, 0.2],
	[0.3, 0.4],
	[0.5, 0.6],
	[0.7, 0.8]])

print("Original matrix: \n", A)

# calculate pseudoinverse
B = pinv(A)
print("pseudoinverse of A: \n", B)

Original matrix: 
 [[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
pseudoinverse of A: 
 [[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


## Calculate Pseudo-inverse of a matrix using SVD

In [14]:
# Pseudoinverse via SVD
from numpy import array
from numpy.linalg import svd
from numpy import zeros
from numpy import diag

# define matrix
A = array([
	[0.1, 0.2],
	[0.3, 0.4],
	[0.5, 0.6],
	[0.7, 0.8]])
print("Original matrix: \n", A)

# calculate svd
U, s, VT = svd(A)

# reciprocals of s
d = 1.0 / s
print("reciprocals of s: \n", d)


# create m x n D matrix
D = zeros(A.shape)

# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = diag(d)

# calculate pseudoinverse
B = VT.T.dot(D.T).dot(U.T)
print("pseudoinverse of A: \n", B)

Original matrix: 
 [[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
reciprocals of s: 
 [ 0.70081527 15.95333376]
pseudoinverse of A: 
 [[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


## SVD for Dimensionality Reduction
<br>A popular application of SVD is for dimensionality reduction.
<br>Data with a large number of features, such as more features (columns) than observations (rows) may be reduced to a smaller subset of features that are most relevant to the prediction problem.
<br><br>
The result is a matrix with a lower rank that is said to approximate the original matrix

In [16]:
from numpy import array
from sklearn.decomposition import TruncatedSVD

# define array
A = array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print("Original matrix: \n", A)

# svd
svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)
print("Transformed version of the original matrix: \n", result)

Original matrix: 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
Transformed version of the original matrix: 
 [[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


# References

[numpy.linalg.svd](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.svd.html)<br>
[numpy.matrix.H API](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.matrix.H.html)<br>
[numpy.diag](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diag.html)<br>
[numpy.linalg.pinv](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.pinv.html)<br>
[sklearn.decomposition.TruncatedSVD](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html)
